### ISSUE TITLE
Collection error

### ISSUE THREAD

**Issue by edavalosanaya** [oele-isis-vanderbilt/ChimeraPy#155]
When using ChimeraPy v0.0.10, the system generates the follow error when collecting (causing complete data failure):

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\student\anaconda3\envs\reading_project_10\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\student\anaconda3\envs\reading_project_10\lib\site-packages\chimerapy\data_handlers.py", line 55, in run
    self.records[data_chunk["name"]].write(data_chunk)
  File "C:\Users\student\anaconda3\envs\reading_project_10\lib\site-packages\chimerapy\records\tabular_record.py", line 46, in write
    df.to_csv(
  File "C:\Users\student\anaconda3\envs\reading_project_10\lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\student\anaconda3\envs\reading_project_10\lib\site-packages\pandas\core\generic.py", line 3720, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "C:\Users\student\anaconda3\envs\reading_project_10\lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\student\anaconda3\envs\reading_project_10\lib\site-packages\pandas\io\formats\format.py", line 1189, in to_csv
    csv_formatter.save()
  File "C:\Users\student\anaconda3\envs\reading_project_10\lib\site-packages\pandas\io\formats\csvs.py", line 241, in save
    with get_handle(
  File "C:\Users\student\anaconda3\envs\reading_project_10\lib\site-packages\pandas\io\common.py", line 734, in get_handle
    check_parent_directory(str(handle))
  File "C:\Users\student\anaconda3\envs\reading_project_10\lib\site-packages\pandas\io\common.py", line 597, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'C:\Users\student\AppData\Local\Temp\tmp14q5xi9i\shimmer'
```

And this,

```
Traceback (most recent call last):
  File "C:\Users\student\Documents\GitHub\reading_experiment_codes\run.py", line 171, in <module>
    manager.collect()
  File "C:\Users\student\anaconda3\envs\reading_project_10\lib\site-packages\chimerapy\manager.py", line 771, in collect
    self.server.move_transfer_files(self.logdir, unzip)
  File "C:\Users\student\anaconda3\envs\reading_project_10\lib\site-packages\chimerapy\networking\server.py", line 419, in move_transfer_files
    shutil.unpack_archive(filepath, named_dst)
  File "C:\Users\student\anaconda3\envs\reading_project_10\lib\shutil.py", line 1306, in unpack_archive
    func(filename, extract_dir, **kwargs)
  File "C:\Users\student\anaconda3\envs\reading_project_10\lib\shutil.py", line 1200, in _unpack_zipfile
    raise ReadError("%s is not a zip file" % filename)
shutil.ReadError: C:\Users\student\AppData\Local\Temp\tmpl36osss6\_tmp9r9g9rot.zip is not a zip fil
```

**Comment by edavalosanaya** [comment]
Addressed by Node refactoring
