### ISSUE TITLE
TimeoutError: Connecting to manager using `cp-worker` entrypoint fails 

### ISSUE THREAD

**Issue by umesh-timalsina** [oele-isis-vanderbilt/ChimeraPy#198]
### Script
```python
>>> import chimerapy as cp
>>> m = cp.Manager("cp-logs", port=9001)
2023-06-23 15:46:51 [DEBUG] chimerapy-networking: <Server Manager>: running at 192.168.0.66:9001
2023-06-23 15:46:51 [INFO] chimerapy: Manager started at 192.168.0.66:9001
```

### CLI
```sh
$ cp-worker --name linux --id linux --zeroconf True
2023-06-23 15:47:39 [DEBUG] chimerapy-worker.linux: Log receiver started at port 59431
2023-06-23 15:47:39 [DEBUG] chimerapy-worker.linux.server: <Server linux>: running at 192.168.0.66:38159
2023-06-23 15:47:39 [INFO] chimerapy-worker.linux: Worker linux running HTTP server at             192.168.0.66:38159
Traceback (most recent call last):
  File "/home/umesh/micromamba/envs/chimerapy-dev/bin/cp-worker", line 8, in <module>
    sys.exit(main())
  File "/home/umesh/isis/oele-isis/ChimeraPy/chimerapy/entry/worker.py", line 46, in main
    worker.connect(method="zeroconf")
  File "/home/umesh/isis/oele-isis/ChimeraPy/chimerapy/worker/worker.py", line 276, in connect
    return future.result(timeout=timeout)
  File "/home/umesh/micromamba/envs/chimerapy-dev/lib/python3.9/concurrent/futures/_base.py", line 448, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError

```

**Comment by edavalosanaya** [comment]
Thanks for pointing it out, will address it today or tomorrow.

**Comment by edavalosanaya** [comment]
Hello @umesh-timalsina

I just realized that this is the correct behavior. That is because, during the refactoring of the Manager (PR #194), I made Zeroconf have to be enabled/disabled due to its possible large CPU footprint. By default, Zeroconf is disabled therefore you will need to enable it. 

This is how you must run it now:

```bash
>>> m = cp.Manager("test", port=9001)
2023-06-26 11:09:11 [DEBUG] chimerapy-networking: <Server Manager>: running at 10.66.199.67:9001
2023-06-26 11:09:11 [INFO] chimerapy: Manager started at 10.66.199.67:9001
>>> m.zeroconf(enable=True)
2023-06-26 11:09:20 [INFO] chimerapy: Manager started Zeroconf Service named chimerapy-4740._http._tcp.local.
True
```

```bash
$ cp-worker --name linux --id linux --zeroconf True
2023-06-26 11:10:25 [DEBUG] chimerapy-worker.linux: Log receiver started at port 59661
2023-06-26 11:10:25 [DEBUG] chimerapy-worker.linux.server: <Server linux>: running at 10.66.199.67:42411
2023-06-26 11:10:25 [INFO] chimerapy-worker.linux: Worker linux running HTTP server at 10.66.199.67:42411
2023-06-26 11:10:25 [INFO] chimerapy-worker.linux: chimerapy zeroconf service detected: ServiceInfo(type='_http._tcp.local.', name='chimerapy-4740._http._tcp.local.', addresses=[b'\nB\xc7C'], port=9001, weig
ht=0, priority=0, server='chimerapy-4740._http._tcp.local.', properties={b'path': b'/home/eduardo/GitHub/ChimeraPy/test/chimerapy-2023_06_26_11_09_11-4740', b'timestamp': b'2023_06_26_11_09_11'}, interface_i
ndex=None)
2023-06-26 11:10:27 [INFO] chimerapy-worker.linux: <Worker name=linux id=linux>-HttpClientService: enabling logs push to Manager
2023-06-26 11:10:27 [INFO] chimerapy-worker.linux: <Worker name=linux id=linux>-HttpClientService: connection successful to Manager @ 10.66.199.67:9001.
2023-06-26 11:10:27 [DEBUG] chimerapy-worker.linux: <Worker name=linux id=linux>-HttpClientService: connected via zeroconf: True
2023-06-26 11:10:27 [DEBUG] chimerapy-worker.linux: <Worker name=linux id=linux>-HttpClientService: successful zeroconf: True
2023-06-26 11:10:27 [DEBUG] chimerapy-worker.linux: <Worker name=linux id=linux>: Idle

```

Later, when updating the documentation, I will add this nugget of information. Sorry for the trouble.

## References
[Zeroconf Enable/Disable API](https://github.com/oele-isis-vanderbilt/ChimeraPy/blob/5fbd64eb81cbf641ebbe2d4b0caa0ad223dddf41/chimerapy/manager/manager.py#L301).

**Comment by umesh-timalsina** [comment]
I see, if that is the case, would it be worth while to introduce it in the `ManagerState`?

```py
class ManagerState:
   ...
   zeroconf_discovery: bool
   ....
```
